# Generated by Django 4.1.7 on 2023-03-29 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choice',
            new_name='question_choice',
        ),
    ]
