# Generated by Django 4.1.7 on 2023-03-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_choice_question_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_gay',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_choice',
            field=models.BooleanField(),
        ),
    ]
