# Generated by Django 4.1.7 on 2023-03-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_is_gay_alter_question_question_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_choice',
        ),
    ]
